spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/food?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root  # -> ?? ???? MySQL username ??
    password: lkmasz12  # -> ?? ???? MySQL ???? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
